name: p1_moviles
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc:
  equatable:
  flutter_bloc:
  avatar_glow:
  record:
  url_launcher:
  http:
  permission_handler:
  firebase_core:
  cloud_firestore:
  firebase_auth:
  google_sign_in:
  flutterfire_ui:
  firebase_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/record.png
    - assets/icon/spotify.png
    - assets/icon/apple.png
    - assets/icon/linktree.png
    - assets/icon/bg.gif
